name: Build debug APK file
on:
  workflow_dispatch:

env:
  ADMOB_APP_ID: ${{ secrets.ADMOB_APP_ID }}
  DEVICE_TEST_AD_ID: ${{ secrets.DEVICE_TEST_AD_ID }}
  ADMOB_OPEN_APP_ID: ${{ secrets.ADMOB_OPEN_APP_TEST_ID }}
  FIREBASE_GOOGLE_SERVICES: ${{ secrets.FIREBASE_GOOGLE_SERVICES }}

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          chmod +x .github/set-key.sh
          .github/set-key.sh
        shell: bash

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "ADMOB_APP_ID=${{ secrets.ADMOB_APP_ID }}" > local.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Set app properties
        id: properties
        run: |
          echo "versionName=$(./gradlew -q printVersionInfo | grep 'VersionName' | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "versionCode=$(./gradlew -q printVersionInfo | grep 'VersionCode' | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: compara-precos_debug_v${{ steps.properties.outputs.versionName }}_vc${{ steps.properties.outputs.versionCode }}_branch_${{ steps.properties.outputs.branch }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk