name: Run UI and Unit tests CI

on:
  pull_request:
    branches:
      - develop

env:
  DEVICE_TEST_AD_ID: ${{ secrets.DEVICE_TEST_AD_ID }}
  ADMOB_OPEN_APP_TEST_ID: ${{ secrets.ADMOB_OPEN_APP_TEST_ID }}
  ADMOB_OPEN_APP_ID: ${{ secrets.ADMOB_OPEN_APP_ID }}
  FIREBASE_GOOGLE_SERVICES: ${{ secrets.FIREBASE_GOOGLE_SERVICES }}

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Setup checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          chmod +x .github/set-key.sh
          .github/set-key.sh
        shell: bash

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2.25.0
        with:
          api-level: 30
          arch: x86_64
          channel: stable
          target: google_apis
          profile: pixel_6
          avd-name: Test_Pixel6_Google_fhd_2
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: ./gradlew jacocoTestReport

      - name: Generate UI tests jacoco report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: android-ui-tests-reports
          path: '**/build/reports/androidTests/'

      - name: Generate Unit tests jacoco report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: android-unit-tests-reports
          path: '**/build/reports/tests/testDebugUnitTest'